// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxALkYdxx4zPDgS70HmBXPWfvYAcaBQM',
    appId: '1:713065625334:web:5d564024d1c2b62cc6ded7',
    messagingSenderId: '713065625334',
    projectId: 'batami',
    authDomain: 'batami.firebaseapp.com',
    storageBucket: 'batami.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIPDBESL7cRykMWT5YwxjxSmhnBd6zkcA',
    appId: '1:713065625334:android:cd9c7a3de5cfd5e4c6ded7',
    messagingSenderId: '713065625334',
    projectId: 'batami',
    storageBucket: 'batami.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt60hz4MPVnNoll85WaUzBB8Pd_hnafPs',
    appId: '1:713065625334:ios:18bc8ef83c7a781ec6ded7',
    messagingSenderId: '713065625334',
    projectId: 'batami',
    storageBucket: 'batami.appspot.com',
    iosClientId: '713065625334-vslt5je55e49i5jg5e020p563kt95ovg.apps.googleusercontent.com',
    iosBundleId: 'io.cordova.Batami',
  );
}
